# Generated by Django 3.1.2 on 2020-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaad', '0003_auto_20201120_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
